import React, { useState, useEffect } from 'react';
import { X, EyeOff, Eye, ChevronDown } from 'lucide-react';

export function UserModal({ isOpen, onClose, mode = 'create', userData = null, onSave }) {
    const isReadOnly = mode === 'view';
    const title = mode === 'create' ? 'Novo usuário' : mode === 'edit' ? 'Editar usuário' : 'Usuário';

    const [name, setName] = useState('');
    const [access, setAccess] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [showPassword, setShowPassword] = useState(false);

    useEffect(() => {
        if (isOpen) {
            // eslint-disable-next-line react-hooks/set-state-in-effect
            setName(userData?.name || '');
            setAccess(userData?.access === 'Administrador' ? 'admin' : userData?.access === 'Desenvolvedor' ? 'dev' : '');
            setEmail(userData?.email || '');
            setPassword('');
            setShowPassword(false);
        }
    }, [isOpen, userData]);

    if (!isOpen) return null;

    // Helper syntax to get initials
    const getInitials = (nameStr) => {
        if (!nameStr) return '??';
        const parts = nameStr.trim().split(' ').filter(Boolean);
        if (parts.length === 1) return parts[0].substring(0, 1).toUpperCase();
        return (parts[0].substring(0, 1) + parts[parts.length - 1].substring(0, 1)).toUpperCase();
    };

    const displayInitials = getInitials(name);

    const handleSave = () => {
        if (!name || !access || !email || (!password && mode === 'create')) {
            alert('Por favor, preencha todos os campos obrigatórios.');
            return;
        }

        const formattedAccess = access === 'admin' ? 'Administrador' : access === 'dev' ? 'Desenvolvedor' : 'Designer';

        const newUser = {
            id: userData?.id || Date.now(),
            name,
            email,
            access: formattedAccess,
            password: password || undefined,
            color: userData?.color || 'bg-blue-500', // Mock dynamic color or keep existing
            // initials will be generated by the parent or getter
        };

        if (onSave) {
            onSave(newUser, mode);
        }
        onClose();
    };

    return (
        <div className="fixed inset-0 z-[999] bg-[#0b1120]/80 backdrop-blur-sm flex items-center justify-center p-4">
            {/* Modal Container */}
            <div className="w-full max-w-[420px] bg-[#1e252b] rounded-2xl border border-white/10 shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">

                {/* Header */}
                <div className="p-6 pb-4 flex justify-between items-start">
                    <div>
                        <h2 className="text-xl font-bold text-white mb-1">{title}</h2>
                        <p className="text-xs text-[#94a3b8]">Descrição</p>
                    </div>
                    <button
                        onClick={onClose}
                        className="text-slate-400 hover:text-white transition-colors"
                    >
                        <X size={20} />
                    </button>
                </div>

                {/* Avatar */}
                <div className="flex justify-center py-4">
                    <div className={`w-24 h-24 rounded-full ${userData?.color || 'bg-[#3b82f6]'} text-white flex items-center justify-center text-4xl font-semibold shadow-lg shadow-blue-500/20`}>
                        {displayInitials}
                    </div>
                </div>

                {/* Form Fields */}
                <div className="px-6 py-2 space-y-5">

                    {/* Display Name */}
                    <div className="space-y-1.5">
                        <label className="text-sm font-semibold text-slate-200">
                            Nome de exibição <span className="text-red-500">*</span>
                        </label>
                        <input
                            type="text"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            placeholder="Digite..."
                            readOnly={isReadOnly}
                            className={`w-full bg-[#111822] border border-white/10 rounded-lg px-4 py-3 text-[13px] text-white focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all font-medium ${isReadOnly ? 'opacity-80 cursor-not-allowed' : ''}`}
                        />
                    </div>

                    {/* Access */}
                    <div className="space-y-1.5">
                        <label className="text-sm font-semibold text-slate-200">
                            Acesso <span className="text-red-500">*</span>
                        </label>
                        <div className="relative">
                            <select
                                disabled={isReadOnly}
                                value={access}
                                onChange={(e) => setAccess(e.target.value)}
                                className={`appearance-none w-full bg-[#111822] border border-white/10 rounded-lg px-4 py-3 text-[13px] text-slate-300 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all font-medium ${isReadOnly ? 'opacity-80 cursor-not-allowed' : ''}`}
                            >
                                <option value="">Selecione</option>
                                <option value="admin">Administrador</option>
                                <option value="dev">Desenvolvedor</option>
                                <option value="designer">Designer</option>
                            </select>
                            <ChevronDown size={16} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
                        </div>
                    </div>

                    {/* Email */}
                    <div className="space-y-1.5">
                        <label className="text-sm font-semibold text-slate-200">
                            E-mail <span className="text-red-500">*</span>
                        </label>
                        <input
                            type="email"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            placeholder="Digite..."
                            readOnly={isReadOnly}
                            className={`w-full bg-[#111822] border border-white/10 rounded-lg px-4 py-3 text-[13px] text-white focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all font-medium ${isReadOnly ? 'opacity-80 cursor-not-allowed' : ''}`}
                        />
                    </div>

                    {/* Password */}
                    <div className="space-y-1.5">
                        <label className="text-sm font-semibold text-slate-200">
                            Senha {mode === 'create' && <span className="text-red-500">*</span>}
                        </label>
                        <div className="relative">
                            <input
                                type={showPassword ? 'text' : 'password'}
                                value={isReadOnly && userData ? '********' : password}
                                onChange={(e) => setPassword(e.target.value)}
                                placeholder="Digite..."
                                readOnly={isReadOnly}
                                className={`w-full bg-[#111822] border border-white/10 rounded-lg px-4 py-3 text-[13px] text-white focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all font-medium ${userData && isReadOnly ? 'tracking-[0.15em]' : ''} ${isReadOnly ? 'opacity-80 cursor-not-allowed' : ''}`}
                            />
                            {!isReadOnly && (
                                <button
                                    onClick={() => setShowPassword(!showPassword)}
                                    className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white transition-colors"
                                >
                                    {showPassword ? <Eye size={16} /> : <EyeOff size={16} />}
                                </button>
                            )}
                        </div>
                    </div>

                </div>

                {/* Footer Buttons */}
                <div className="p-6 pt-4 mt-2 flex justify-end gap-3 items-center">
                    <button
                        onClick={onClose}
                        className="text-[15px] font-semibold text-white hover:text-slate-300 px-4 py-2 transition-colors"
                    >
                        Cancelar
                    </button>
                    {!isReadOnly && (
                        <button
                            onClick={handleSave}
                            className="bg-[#0ea5e9] hover:bg-[#0284c7] text-white text-[15px] font-semibold px-8 py-2.5 rounded-xl shadow-lg shadow-sky-500/20 transition-all active:scale-95"
                        >
                            Salvar
                        </button>
                    )}
                </div>

            </div>
        </div>
    );
}
